/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BarSelection = IDL.Record({
  'diameter' : IDL.Float64,
  'quantity' : IDL.Nat,
});
export const ShearAssessment = IDL.Record({
  'shearSafe' : IDL.Bool,
  'shearStressTc' : IDL.Float64,
  'shearCapacityVc' : IDL.Float64,
  'percentageSteel' : IDL.Float64,
});
export const BeamCalculation = IDL.Record({
  'adoptedAst' : IDL.Float64,
  'factoredShear' : IDL.Float64,
  'actualMomentResistance' : IDL.Float64,
  'overallSafeForBending' : IDL.Bool,
  'minimumAst' : IDL.Float64,
  'isDoublyReinforced' : IDL.Bool,
  'safeMoment' : IDL.Float64,
  'providedSteelMoreThanMin' : IDL.Bool,
  'limitingMoment' : IDL.Float64,
  'requiredAst' : IDL.Float64,
  'isUnsafe' : IDL.Bool,
  'barSelection' : BarSelection,
  'effectiveDepthAdopted' : IDL.Float64,
  'shearAssessment' : ShearAssessment,
  'neutralAxisDepth' : IDL.Float64,
});
export const BeamInput = IDL.Record({
  'fy' : IDL.Float64,
  'fck' : IDL.Float64,
  'factoredMomentMu' : IDL.Float64,
  'depthD' : IDL.Float64,
  'factoredShearVu' : IDL.Float64,
  'beamDesignation' : IDL.Text,
  'breadthB' : IDL.Float64,
  'effectiveDepthD' : IDL.Float64,
});
export const BeamResult = IDL.Record({
  'output' : BeamCalculation,
  'input' : BeamInput,
});

export const idlService = IDL.Service({
  'getCalculationByDesignation' : IDL.Func([IDL.Text], [BeamResult], ['query']),
  'getCalculations' : IDL.Func([], [IDL.Vec(BeamResult)], ['query']),
  'storeCalculation' : IDL.Func([BeamInput, BeamCalculation], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BarSelection = IDL.Record({
    'diameter' : IDL.Float64,
    'quantity' : IDL.Nat,
  });
  const ShearAssessment = IDL.Record({
    'shearSafe' : IDL.Bool,
    'shearStressTc' : IDL.Float64,
    'shearCapacityVc' : IDL.Float64,
    'percentageSteel' : IDL.Float64,
  });
  const BeamCalculation = IDL.Record({
    'adoptedAst' : IDL.Float64,
    'factoredShear' : IDL.Float64,
    'actualMomentResistance' : IDL.Float64,
    'overallSafeForBending' : IDL.Bool,
    'minimumAst' : IDL.Float64,
    'isDoublyReinforced' : IDL.Bool,
    'safeMoment' : IDL.Float64,
    'providedSteelMoreThanMin' : IDL.Bool,
    'limitingMoment' : IDL.Float64,
    'requiredAst' : IDL.Float64,
    'isUnsafe' : IDL.Bool,
    'barSelection' : BarSelection,
    'effectiveDepthAdopted' : IDL.Float64,
    'shearAssessment' : ShearAssessment,
    'neutralAxisDepth' : IDL.Float64,
  });
  const BeamInput = IDL.Record({
    'fy' : IDL.Float64,
    'fck' : IDL.Float64,
    'factoredMomentMu' : IDL.Float64,
    'depthD' : IDL.Float64,
    'factoredShearVu' : IDL.Float64,
    'beamDesignation' : IDL.Text,
    'breadthB' : IDL.Float64,
    'effectiveDepthD' : IDL.Float64,
  });
  const BeamResult = IDL.Record({
    'output' : BeamCalculation,
    'input' : BeamInput,
  });
  
  return IDL.Service({
    'getCalculationByDesignation' : IDL.Func(
        [IDL.Text],
        [BeamResult],
        ['query'],
      ),
    'getCalculations' : IDL.Func([], [IDL.Vec(BeamResult)], ['query']),
    'storeCalculation' : IDL.Func([BeamInput, BeamCalculation], [], []),
  });
};

export const init = ({ IDL }) => { return []; };