/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BarSelection { 'diameter' : number, 'quantity' : bigint }
export interface BeamCalculation {
  'adoptedAst' : number,
  'factoredShear' : number,
  'actualMomentResistance' : number,
  'overallSafeForBending' : boolean,
  'minimumAst' : number,
  'isDoublyReinforced' : boolean,
  'safeMoment' : number,
  'providedSteelMoreThanMin' : boolean,
  'limitingMoment' : number,
  'requiredAst' : number,
  'isUnsafe' : boolean,
  'barSelection' : BarSelection,
  'effectiveDepthAdopted' : number,
  'shearAssessment' : ShearAssessment,
  'neutralAxisDepth' : number,
}
export interface BeamInput {
  'fy' : number,
  'fck' : number,
  'factoredMomentMu' : number,
  'depthD' : number,
  'factoredShearVu' : number,
  'beamDesignation' : string,
  'breadthB' : number,
  'effectiveDepthD' : number,
}
export interface BeamResult { 'output' : BeamCalculation, 'input' : BeamInput }
export interface ShearAssessment {
  'shearSafe' : boolean,
  'shearStressTc' : number,
  'shearCapacityVc' : number,
  'percentageSteel' : number,
}
export interface _SERVICE {
  'getCalculationByDesignation' : ActorMethod<[string], BeamResult>,
  'getCalculations' : ActorMethod<[], Array<BeamResult>>,
  'storeCalculation' : ActorMethod<[BeamInput, BeamCalculation], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];